// Code generated by https://github.com/teal-finance/emo/blob/main/codegen/golang/gen.go ; DO NOT EDIT.

package emo

func (zone Zone) Info(args ...any) Event {
	return processEvent("ℹ️", zone, false, args)
}

func (zone Zone) Warning(args ...any) Event {
	return processEvent("🔔", zone, false, args)
}

func (zone Zone) Error(args ...any) Event {
	return processEvent("💢", zone, true, args)
}

func (zone Zone) Query(args ...any) Event {
	return processEvent("🗄️", zone, false, args)
}

func (zone Zone) QueryError(args ...any) Event {
	return processEvent("🗄️", zone, true, args)
}

func (zone Zone) Encrypt(args ...any) Event {
	return processEvent("🎼", zone, false, args)
}

func (zone Zone) EncryptError(args ...any) Event {
	return processEvent("🎼", zone, true, args)
}

func (zone Zone) Decrypt(args ...any) Event {
	return processEvent("🗝️", zone, false, args)
}

func (zone Zone) DecryptError(args ...any) Event {
	return processEvent("🗝️", zone, true, args)
}

func (zone Zone) Time(args ...any) Event {
	return processEvent("⏱️", zone, false, args)
}

func (zone Zone) TimeError(args ...any) Event {
	return processEvent("⏱️", zone, true, args)
}

func (zone Zone) Param(args ...any) Event {
	return processEvent("📩", zone, false, args)
}

func (zone Zone) ParamError(args ...any) Event {
	return processEvent("📩", zone, true, args)
}

func (zone Zone) Debug(args ...any) Event {
	return processEvent("💊", zone, false, args)
}

func (zone Zone) State(args ...any) Event {
	return processEvent("📢", zone, false, args)
}

func (zone Zone) Save(args ...any) Event {
	return processEvent("💾", zone, false, args)
}

func (zone Zone) Delete(args ...any) Event {
	return processEvent("❌", zone, false, args)
}

func (zone Zone) Data(args ...any) Event {
	return processEvent("💼", zone, false, args)
}

func (zone Zone) Line(args ...any) Event {
	return processEvent("➖", zone, false, args)
}

func (zone Zone) Init(args ...any) Event {
	return processEvent("🎬", zone, false, args)
}

func (zone Zone) Update(args ...any) Event {
	return processEvent("🆙", zone, false, args)
}

func (zone Zone) Ok(args ...any) Event {
	return processEvent("🆗", zone, false, args)
}

func (zone Zone) Build(args ...any) Event {
	return processEvent("🔧", zone, false, args)
}

func (zone Zone) Aconstructor(args ...any) Event {
	return processEvent("🛠️", zone, false, args)
}

func (zone Zone) NotFound(args ...any) Event {
	return processEvent("🚫", zone, false, args)
}

func (zone Zone) Found(args ...any) Event {
	return processEvent("👁️‍🗨️", zone, false, args)
}

func (zone Zone) Result(args ...any) Event {
	return processEvent("📌", zone, false, args)
}

func (zone Zone) Input(args ...any) Event {
	return processEvent("📥", zone, false, args)
}

func (zone Zone) Output(args ...any) Event {
	return processEvent("📤", zone, false, args)
}

func (zone Zone) Function(args ...any) Event {
	return processEvent("🔨", zone, false, args)
}

func (zone Zone) Key(args ...any) Event {
	return processEvent("🔑", zone, false, args)
}

func (zone Zone) AccessToken(args ...any) Event {
	return processEvent("🔑", zone, false, args)
}

func (zone Zone) RefreshToken(args ...any) Event {
	return processEvent("🗝️", zone, false, args)
}

func (zone Zone) Transmit(args ...any) Event {
	return processEvent("📡", zone, false, args)
}

func (zone Zone) Start(args ...any) Event {
	return processEvent("🏁", zone, false, args)
}

func (zone Zone) Stop(args ...any) Event {
	return processEvent("🛑", zone, false, args)
}

func (zone Zone) ArrowIn(args ...any) Event {
	return processEvent("=>", zone, false, args)
}

func (zone Zone) ArrowOut(args ...any) Event {
	return processEvent("<=", zone, false, args)
}

func (zone Zone) SmallArrowIn(args ...any) Event {
	return processEvent("->", zone, false, args)
}

func (zone Zone) SmallArrowOut(args ...any) Event {
	return processEvent("<-", zone, false, args)
}

func (zone Zone) RequestGet(args ...any) Event {
	return processEvent("🔷", zone, false, args)
}

func (zone Zone) RequestPost(args ...any) Event {
	return processEvent("🔶", zone, false, args)
}
