// Code generated by ref/codegen.go; DO NOT EDIT.
//go:build emo
// +build emo

package emo

func (zone Zone) Info(args ...interface{}) Event {
	return processEvent("ℹ️", zone, false, args)
}

func (zone Zone) Warning(args ...interface{}) Event {
	return processEvent("🔔", zone, false, args)
}

func (zone Zone) Error(args ...interface{}) Event {
	return processEvent("💢", zone, true, args)
}

func (zone Zone) Query(args ...interface{}) Event {
	return processEvent("🗄️", zone, false, args)
}

func (zone Zone) QueryError(args ...interface{}) Event {
	return processEvent("🗄️", zone, true, args)
}

func (zone Zone) Encrypt(args ...interface{}) Event {
	return processEvent("🎼", zone, false, args)
}

func (zone Zone) EncryptError(args ...interface{}) Event {
	return processEvent("🎼", zone, true, args)
}

func (zone Zone) Decrypt(args ...interface{}) Event {
	return processEvent("🗝️", zone, false, args)
}

func (zone Zone) DecryptError(args ...interface{}) Event {
	return processEvent("🗝️", zone, true, args)
}

func (zone Zone) Time(args ...interface{}) Event {
	return processEvent("⏱️", zone, false, args)
}

func (zone Zone) TimeError(args ...interface{}) Event {
	return processEvent("⏱️", zone, true, args)
}

func (zone Zone) Param(args ...interface{}) Event {
	return processEvent("📥", zone, false, args)
}

func (zone Zone) ParamError(args ...interface{}) Event {
	return processEvent("📥", zone, true, args)
}

func (zone Zone) Debug(args ...interface{}) Event {
	return processEvent("💊", zone, false, args)
}
